### ISSUE TITLE
"￥" (两个横杠)符号有的时候变成了一个横杠

### ISSUE THREAD

**Issue by CrossYourSoul** [loperSeven/PriceTextView#1]
"￥" (两个横杠)符号有的时候变成了一个横杠

**Comment by loper7** [comment]
![image](https://user-images.githubusercontent.com/20430552/47062478-e0546a00-d208-11e8-829c-b6c9840f9790.png)
在编译器里面通过键盘打出“￥“这个符号只有一个横杠呢
